### ISSUE TITLE
无法调用ocr软件

### ISSUE THREAD

**Issue by DWCY3574** [UB-Mannheim/zotero-ocr#69] opened 2024-04-20 16:24 UTC
只能拆分图片

**Comment by aborel** [comment] 2024-04-21 05:45
Can you explain your problem in more details? Zotero's documentation has good guidelines on how to report problems: https://www.zotero.org/support/reporting_problems#provide_steps_to_reproduce

**Comment by chenziliang0725** [comment] 2024-04-26 05:57
是的，只能拆分图片，无法ocr，，之前的版本是可以的，更新了之后就不行了

**Comment by aborel** [comment] 2024-04-26 06:11
Sorry, I still don't understand the issue.
Can you explain as follows:
1) report exactly what you are doing (what menu is selected, any relevant options, etc.)
2) explain what result you were expecting
3) explain what you observe (please use different words instead of what was written in the first 2 messages, the Google translation is not clear to me)

**Comment by chenziliang0725** [comment] 2024-04-26 06:35
只有当使用zotero7beta68版本和zotero-ocr7.0版本时，是可以正常使用的。
当我的zotero版本高于beta68，或者zotero-ocr为7.1版本时，都不能正常使用，只能拆分出图片，而不能ocr

**Comment by chenziliang0725** [comment] 2024-04-26 06:36
It can only be used normally when using zotro7beta68 and zotro-ocr7.0 versions.

When my zotro version is higher than beta68 or zotro ocr is 7.1, it cannot be used normally and can only be split into images, not OCR

**Comment by chenziliang0725** [comment] 2024-04-26 06:38
Can the author perform multi-threaded processing when using OCR? The current plugin is single threaded OCR, which is a bit slow.

If this feature could be provided, it would be perfect. Thank you very much

**Comment by stweil** [comment] 2024-04-26 06:40
Is this a duplicate of issue #70?

**Comment by aborel** [comment] 2024-04-26 06:44
Thanks a lot for these details!
Yes, I think the reported bug is the same as https://github.com/UB-Mannheim/zotero-ocr/issues/70 , I'm getting closer to resolving it.

As for multiprocessing, this should be a different issue. @chenziliang0725 you may open a new one to suggest this new functionality.

**Comment by aborel** [comment] 2024-04-28 08:01
You can now try version 0.7.2
Please let us know how it works for you.

**Comment by chenziliang0725** [comment] 2024-04-28 08:04
ok，thanks！

**Closed** 2024-05-24 16:10 UTC
Labels: duplicate, question
