### ISSUE TITLE
Zotero-ocr not compatible with latest beta 6

### ISSUE THREAD

**Issue by cjpoor** [UB-Mannheim/zotero-ocr#37] opened 2022-02-20 00:40 UTC
Attempting to install zotero-ocr-0.5.0.xpi on 
Zotero 6.0-beta.1+8c846468f
gives the message that this add-on is not compatible with this version of Zotero.
See this discussion
https://forums.zotero.org/discussion/94617/all-plugins-removed-from-zotero-6-0-beta-1-c6d03753f#latest

**Comment by bbraunj** [comment] 2022-02-23 14:12
@cjpoor If you build manually from #38, you should be able to install the resulting .xpi on beta 6.

**Comment by cjpoor** [comment] 2022-02-24 00:55
@bbraunj Thanks. How do I build manually?

**Comment by bbraunj** [comment] 2022-02-24 13:34
@cjpoor In the terminal:
```bash
$ git clone https://github.com/bbraunj/zotero-ocr.git
$ cd zotero-ocr
$ git checkout zotero-beta-6
$ ./build.sh
```
This should produce a .xpi in that directory.

**Comment by cjpoor** [comment] 2022-02-25 01:33
Great. Thank you . It works!

**Comment by cjpoor** [comment] 2022-02-28 00:34
Will this zotero-beta-6-ocr work with Zotero 5?

**Comment by ShengyeTao** [comment] 2022-03-14 15:07
@bbraunj nice job, thanks a lot, it actually do me a big favor.

**Comment by cjpoor** [comment] 2022-03-14 19:49
Thank you :-)

**Comment by charmarkk** [comment] 2022-04-07 01:32
As I try this, I get the following error on Windows and Linux:

`./build.sh: line 10: zip: command not found`

Am I doing something wrong after entering a version number?

**Comment by cjpoor** [comment] 2022-04-07 03:11
@charmarkk What did you enter for version number? I used "6" (without the quotation marks) and it worked for me on linux Mint, producing ~/zotero-ocr/zotero-ocr-6.xpi

**Comment by vdmeer-rm** [comment] 2022-04-07 10:05
When I try this, I get:  '/build.sh' is not recognized as an internal or external command, operable program or batch file.
I tried just using build.sh - this made me enter a version number. When I picked 6 (or anything else), I could not find the .xpi file. Is there a way you can help me?

**Comment by bbraunj** [comment] 2022-04-07 12:36
@charmarkk You may need to install `zip` through your package manager. On Ubuntu, for example, this looks like:
```
sudo apt install zip unzip
```

**Comment by bbraunj** [comment] 2022-04-07 12:38
@vdmeer-rm What OS are you using?

**Comment by vdmeer-rm** [comment] 2022-04-07 12:41
@bbraunj Windows

**Comment by charmarkk** [comment] 2022-04-07 17:39
> @charmarkk You may need to install `zip` through your package manager. On Ubuntu, for example, this looks like:
> 
> ```
> sudo apt install zip unzip
> ```

I'll try that. I'm almost positive that must be what the issue is - thanks!

> @vdmeer-rm That would be why. Building requires macOS or Linux because it is a bash script. Here is the last build I got.

FWIW I think you can run this on Windows if you install Git Bash, I got through everything except running into the "zip command not found" issue. That said, `zip` may not be a usable command _at all_ on Windows.

**Comment by charmarkk** [comment] 2022-04-09 03:44
> > @charmarkk You may need to install `zip` through your package manager. On Ubuntu, for example, this looks like:
> > ```
> > sudo apt install zip unzip
> > ```
> 
> I'll try that. I'm almost positive that must be what the issue is - thanks!

This was indeed the answer. This would be good documentation, not everyone uses linux or is familiar with that package.

**Comment by dstark** [comment] 2022-04-13 18:45
@bbraunj and @vdmeer-rm, apparently you can build the extension on Windows via the Linux subsystem. Documentation [here](https://www.jdavidstark.com/how-to-extract-text-from-image-only-pdfs-with-zotero#windows) in case it should prove useful to you or others. But hopefully the update to allow the extension in Zotero 6 by default will come along in the near future.

**Comment by zuphilip** [comment] 2022-05-22 17:40
I have mergerd the pull request by @bbraunj and released a new version: https://github.com/UB-Mannheim/zotero-ocr/releases/tag/0.6.0 which should now work again with Zotero 6. (In general it is not needed to create the XPI-file yourself.) Thank you for the intermediate support here as well.

I will close this issue now. Feel free to open another one, if you have any further or follow-up problems.

**Closed by zuphilip** 2022-05-22 17:40 UTC
